name: edu-buddy-ai

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - requests
  - websockets
  - python-dotenv
  - python-sounddevice
  - pip:
      - gTTS
      - faster-whisper
      - openai
      - pyttsx3
      - elevenlabs
      - google-generativeai
      - openai
      - ollama
      - soundfile
      - sounddevice
      - pydub
      - setuptools
      - nvidia-cublas-cu12
      - nvidia-cudnn-cu12
