name: edu-buddy-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - requests
  - websockets
  - python-dotenv
  - python-sounddevice
  - pip:
      - faster-whisper
      - openai
      - pyttsx3
      - setuptools
      - nvidia-cublas-cu12
      - nvidia-cudnn-cu12